name: My First Workflow 

on: push

jobs:
  Say-hello:
    runs-on: ubuntu-latest

    steps:
       - name: Print message
         run: echo "Hello, Github Actions!"

       - name: Print my name
         run: echo "Gaurish"
  Say-bye:
    runs-on: ubuntu-latest

    steps:
       - name: Print message
         run: echo "Hello, Github Actions!"
         

